GET http://localhost:8080/seasons

###
GET http://localhost:8080/episodes/seasons/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvYmlhc3JhcyIsImlhdCI6MTY4MjM2NzY3MX0.pHgtffAkTxkVMfmenimLPIqAxJNkNabOxuqZJdD8tGI



###
GET http://localhost:8080/episodes/seasons/1

###
GET http://localhost:8080/quotes/seasons/1/episodes/1

### SHOULD BE CORRECT
POST  http://localhost:8080/login
Content-Type: application/json

{
  "username": "tobiasras",
  "password": "password"
}

### SHOULD NOT BE CORRECT
POST  http://localhost:8080/login
Content-Type: application/json

{
  "username": "tobiasras",
  "password": "passwordasd"
}


